smartdevicelink/sdl_app_library_guides

docs/Video Streaming for Navigation Apps/Video Streaming/index.md

Fixes #161 
Add clarifying language that setting custom video encoder settings will override head unit values.

Clarify that setting custom encoder settings will override head unit settings

---

docs/Video Streaming for Navigation Apps/Introduction/index.md

Fixes #220 
This PR adds information on how to prevent iOS devices from sleeping when a navigation app is in not in HMI NONE to ensure video data is always streamed.

Add information on how to prevent the device from sleeping on iOS

---

docs/Other SDL Features/Encryption/index.md

Fixes #207 
Added a small how to to the Setting Optional Encryption. This new information tells the user they must start the encryption manually by calling `startRPCEncryption` before they can send encrypted RPCs

Adding info for setup encryption manager manually

---

docs/Getting Started/Connecting to an Infotainment System/index.md

Fixes #224 
Added info on where to add policy table configuration to the policy table, along with a link to SDL server guide Application Policies.
Under Running the SDL App I removed the icon part as it could get confusing especially if you haven't connected your application to that instance of Core yet.

JavaSE connecting to an infotainment system updates

---

docs/Getting Started/Using AOA Protocol/index.md

Fixes #219 
Add a section in Using Android Open Accessory Protocol to inform developers that when using media apps and AOA, their apps will not automatically register by default since there are no Audio streaming methods available, so they have to setRequiresAudioSupport(false) for their connection.

Added info for AOA protocol for media apps

---

docs/Getting Started/Adding the Lock Screen/index.md

Fixes #205 
Added warning to set the `modalPresentationStyle` property of a custom lock screen `UIViewController` to `UIModalPresentationFullScreen` to prevent it from being dismissible by the user.

added note to set modal presentation style of lock screen due to ios 13

---

docs/Other SDL Features/Encryption/index.md

Corrected `sdlManger` instances to `sdlManager`.

fixed sdlmanager typo in encryption guide

---

docs/Getting Started/Integration Basics/index.md
docs/Other SDL Features/Uploading Files/index.md

Fixes #241 
This pull request **fixes existing content**   , **adds new content**.
1. Fixed issue of tag appearing at bottom of IOS guides page `Getting Started/Integration Basics`, as well as fixed numbering of steps under `Creating the SDL Manager`(there are currently two step 11's, I changed the last step to 12)
2. Added section to `Getting Started/Integration Basics` called: `SdlManager builder option` to Android, JavaSE and JavaEE
3. In the java code, I added the required method `managerShouldUpdateLifecycle` to SdlManagerListener.

Added File Manager Config and added more detail to integration basics page for java suite, Fixed 2 minor IOS issues

---

config.json

Removes the Configuring SDL Logging, as there's nothing to put there for JS.

Remove Configuring SDL Logging for JS Suite Docs

---

README.md

Fixes #291 
The main README is updated to include references to the JavaScript Suite guides. In addition, the guide link location pointed to the iOS-specific guide page, and it is now updated to point to the general https://smartdevicelink.com/docs/ URL.

Update main README to include references to JS

---

docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
docs/Displaying a User Interface/Alerts/index.md
docs/Displaying a User Interface/Main Screen Templates/index.md
docs/Displaying a User Interface/Media Clock/index.md
docs/Displaying a User Interface/Scrollable Message/index.md
docs/Displaying a User Interface/Slider/index.md
docs/Displaying a User Interface/Template Subscription Buttons/index.md
docs/Getting Started/Checking Supported Features/index.md
docs/Other SDL Features/Batch Sending RPCs/index.md
docs/Other SDL Features/Creating an App Service/index.md
docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
docs/Other SDL Features/Getting the Navigation Destination/index.md
docs/Other SDL Features/Remote Control Vehicle Features/index.md
docs/Other SDL Features/Retrieving Vehicle Data/index.md
docs/Other SDL Features/Setting the Navigation Destination/index.md
docs/Other SDL Features/Using App Services/index.md
docs/Speech and Audio/Getting Microphone Audio/index.md
docs/Speech and Audio/Playing Spoken Feedback/index.md

Due to the unreleased JS Suite 1.1 new APIs and deprecation of existing APIs, the docs need to be updated to reflect those API changes. This includes using the new send RPC APIs in the code snippets and differentiating between using the 1.0 and the 1.1 versions of the APIs.
Important things to note for other teams' reviews: 
- Added a missing system capability type in the Adaptive Interface Capabilities section, SEAT_LOCATION. java/ios/js additions are included.
- The usage of the new API methods for sending RPCs sequentially and in parallel. 
- The SCM's new methods for exposing missing capabilities

Additions and changes due to new JS 1.1

---

docs/Getting Started/Integration Basics/index.md

Fixes #314 
Add setting Hash Resumption Id when using SdlManager builder to Integration basics guides

Add setting Hash Resumption Id in builder to Integration basics

---

docs/Getting Started/Installation/index.md

Fixes #316 
Adds the simulator stripping script for submitting a manual framework to the app store.

Add the simulator stripping script to the iOS installation guide

---

docs/Speech and Audio/Playing Audio Indications/index.md

Fixes #281
In The Java Suite and JS Suite examples for Audio Indications we are not sending the Alert RPC. This has been added into the respective code snippets to align with the iOS docs

Audio Indications Alignment

---

docs/Other SDL Features/Remote Control Vehicle Features/index.md

Fixes #285 
Update android and java guides to use a OnSystemCapabilityListener rather than getCapability for Remote Control to align with other docs

Use Listener for RemoteControl System Capability

---

docs/Developer Tools/Configuring SDL Logging/index.md

Fixes #352 
This PR notes that the Apple System Log logging target for iOS is now deprecated and changes the OS Log logging target description to state that it is now always the default.

Note that Apple System Log Target is now deprecated

---

docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md

Fixes #361 
Removes references to iOS 9 when referencing haptic input.

Remove references to iOS 9

---

docs/Other SDL Features/Creating an App Service/index.md
docs/Video Streaming for Navigation Apps/Introduction/index.md

Fixes #229 
This PR adds a section to the Introduction for Video Streaming for Navigation apps instructing the developer to cancel their route if the navigation service becomes inactive

Nav service route cancel

---

docs/Other SDL Features/Uploading Files/index.md

Fixes #390
Updates the storage left section in `FileManager` to use the `bytesAvailable` API

Use FileManager.bytesAvailable in java

---

docs/Other SDL Features/Uploading Files/index.md

Fixes #417 
Adds the usage of the overwrite property in SdlFile for the JS suite in the Uploading Files page

Add overwrite usage to JS docs

---

docs/Getting Started/Installation/index.md

Fixes #426 
Removes Accio from the guides because devs don't use it and we now support SPM.

Remove accio installation from the guides

---

config.json
docs/Migrating to Newer SDL Java Suite Versions/Updating to v5.1/index.md

Fixes #434
Adds a 5.1 migration guide for Java Suite

add 5.1 migration guide

---

docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md

Fixes #446 
Add information about the Xcode 12.5 change to `canBecomeFocused` with built-in views.

Add information about Xcode 12.5 canBecomeFocused change

---

docs/Speech and Audio/Setting Up Voice Commands/index.md

Fixes #437 
The JavaScript Suite now supports clearing voice commands by providing an empty array to setVoiceCommands and so the docs have been updated to include this.

Update javascript docs to say that clearing voice commands by sending an empty array is now supported

---

docs/Getting Started/Understanding Permissions/index.md

Fixes #290 
References to FunctionID's GetVehicleData and to the permission status's getIsRpcAllowed have now been fixed in the Understanding Permissions section for the JS suite.
Also fixes an enums property typo

Fix FunctionID and permission status method naming

---

docs/Displaying a User Interface/Alerts and Subtle Alerts/index.md
docs/Displaying a User Interface/Scrollable Message/index.md

Fixes #480
This PR updates some references to raw `SoftButton` objects to show soft button ids that are outside of the restricted range of 0–10000.

Update raw soft button id numbers to be out of the restricted screen manager range

---

docs/Displaying a User Interface/Alerts and Subtle Alerts/index.md
docs/Speech and Audio/Getting Microphone Audio/index.md
docs/Speech and Audio/Playing Audio Indications/index.md
docs/Speech and Audio/Playing Spoken Feedback/index.md
docs/Speech and Audio/Setting Up Voice Commands/index.md

Fixes Issue #510
This pull request adds new content
Added notes about browser compatibility when Manticore testing audio features to 
- [displaying-a-user-interface/alerts-and-subtle-alerts/](https://smartdevicelink.com/en/guides/iOS/displaying-a-user-interface/alerts-and-subtle-alerts/.)
- [speech-and-audio/playing-spoken-feedback/](https://smartdevicelink.com/en/guides/iOS/speech-and-audio/playing-spoken-feedback/  )

Adding notes for browser compatibility with Manticore testing of Audio

---

docs/Getting Started/Connecting to an Infotainment System/index.md

Fixes #518 
This pull request adds new content
* A note is added to the Policy Table Configuration section of the Connecting to an Infotainment System page about need to have the app nickname in the policy table match the app name used in the SdlService class

JavaSE configuration naming clarification

---

docs/Getting Started/Integration Basics - Java/index.md

Fixes #524 
This pull request  **adds new content**.
- A second example is added to the Android Integration Basics guide on how to use an RPC notification listener when creating an `SdlManagerListener` object

Added an additional RPC listener example for a second Android use case

---

docs/Getting Started/Integration Basics - iOS/index.md

Fixes #517
Added a missing return to one of the obj-C examples

bugfix/issue 517 Add Missing Return to objC Example

---

docs/Other SDL Features/Batch Sending RPCs/index.md

subscribeButtonLeft added twice in Array list
Fixes #540
This pull request **fixes existing content** 
Duplicate variable name added to array list in Android/Java in Other SDL Featuers > Batch Sending RPCs: 
`sdlManager.sendRPCs(Arrays.asList(subscribeButtonLeft, subscribeButtonLeft), new OnMultipleRequestListener() {`
changed to:
`sdlManager.sendRPCs(Arrays.asList(subscribeButtonLeft, subscribeButtonRight), new OnMultipleRequestListener() {`

Rename duplicate variable to subscribeButtonRight
