smartdevicelink/sdl_app_library_guides

- docs/Other SDL Features/Remote Control Vehicle Features/index.md
Added platform tags to the **Displaying a User Interface / Remote Control Vehicle Features** section
> Other SDL Features / Remote Control Vehicle Features

- docs/Other SDL Features/Playing Audio Indications/index.md
Added platform tags to the **Displaying a User Interface / Playing Audio Indications** section
> Other SDL Features / Playing Audio Indications

- docs/Other SDL Features/Uploading Files/index.md
Added platform tags to the **Displaying a User Interface / Uploading Files** section
> Other SDL Features / Uploading Files

- docs/Displaying a User Interface/Media Clock/index.md
Added platform tags to the **Displaying a User Interface / Media Clock** section
> Displaying a User Interface / Media Clock

- docs/Getting Started/Installation/index.md
Add Android, JavaSE, and JavaEE installation guides
> Getting Started / Installation

- docs/Getting Started/Installation/index.md
> Add Accio as an iOS distribution method

- README.md
> Update the README to include additional information on tags and best practices

- docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
- docs/Displaying a User Interface/Main Menu/index.md
- docs/Getting Started/Installation/index.md
- docs/Other SDL Features/Creating an App Service/index.md
- docs/Other SDL Features/Remote Control Vehicle Features/index.md
- docs/Other SDL Features/Retrieving Vehicle Data/index.md
- docs/Other SDL Features/Using App Services/index.md
- docs/Video Streaming for Navigation Apps/Audio Streaming/index.md
- docs/Video Streaming for Navigation Apps/Touch Input/index.md
Fixes #42, #43 
This PR targets iOS v6.3 and Android v4.9 releasing in June 2019.
* Dynamic Menu Cell Updating
* SDLAudioStreamManager pushData
* SDLSystemCapabilityManager subscriptions
* SDLManager RPC subscriptions
> iOS and Android June 2019 Content Update

- docs/Frequently Asked Questions/SDL Notifications/index.md
- docs/Frequently Asked Questions/Trusted Router Service/index.md
This pull request **fixes existing content** 
Fixed some MD linting and added some wording to explain acronyms before they are used
> small changes to FAQs

- config.json
- docs/Video Streaming for Navigation Apps/Audio Streaming/index.md
- docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
- docs/Video Streaming for Navigation Apps/Introduction/index.md
- docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
- docs/Video Streaming for Navigation Apps/Video Streaming/index.md
adds / modifies android information to the video streaming folder
> Android video streaming

- docs/Getting Started/Understanding Permissions/index.md
fix a small formatting issue i crated
> fix formatting

- docs/Other SDL Features/Batch Sending RPCs/index.md
- docs/Other SDL Features/Calling a Phone Number/index.md
- docs/Other SDL Features/Creating an App Service/index.md
- docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
- docs/Other SDL Features/Getting In-Car Microphone Audio/index.md
- docs/Other SDL Features/Remote Control Vehicle Features/index.md
- docs/Other SDL Features/Setting the Navigation Destination/index.md
- docs/Other SDL Features/Uploading Files/index.md
- docs/Other SDL Features/Uploading Images/index.md
This pull request **adds content**
> Other Features Updates 

- docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
- Add code to subscribe to capability updates when setting up a listener
> Subscribe to cap when adding a listener

- docs/Developer Tools/Configuring SDL Logging/index.md
This pull request **adds content**
> Developer Tools Updates

- docs/Displaying a User Interface/Alerts/index.md
- docs/Displaying a User Interface/Main Screen Templates/index.md
- docs/Displaying a User Interface/Slider/index.md
- docs/Other SDL Features/Calling a Phone Number/index.md
- docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
- docs/Other SDL Features/Getting In-Car Microphone Audio/index.md
- docs/Other SDL Features/Remote Control Vehicle Features/index.md
- docs/Other SDL Features/Retrieving Vehicle Data/index.md
- docs/Other SDL Features/Setting the Navigation Destination/index.md
- docs/Other SDL Features/Uploading Files/index.md
- docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
adds onError overrides to raw RPC examples for java
> adding onerror overrride

- docs/Getting Started/Example Apps/index.md
- docs/Other SDL Features/Getting In-Car Microphone Audio/index.md
Fixes #57 
This PR is **ready** for review
> Add iOS Example App Debugging / Help Information

- docs/Video Streaming for Navigation Apps/Video Streaming/index.md
This PR just fixes an issue in the sample video streaming code for android
> Fix issue in video streaming sample code

- docs/Getting Started/Integration Basics/index.md
Fixes #97 
Adds information on the file manager configuration
> Add file manager configuration information

- docs/Other SDL Features/Creating an App Service/index.md
Fixes #99 
Fixes initializers for app service manifest
> Fix creating an app service initializers

- docs/Other SDL Features/Creating an App Service/index.md
Fixes #87 
Fixes result code in Creating an App Service section
> Fix result code in creating an app service section

- docs/Other SDL Features/Remote Control Vehicle Features/index.md
Fixes #100
Updated with Fall 2019 release changes for remote control parameter updates.
> Add updated radio / climate parameters

- docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
- docs/Other SDL Features/Creating an App Service/index.md
Fixes #125 
This pull request **updates documentation**
updated documentation to SDLMsgVersion
> Sync Message Version

- docs/Other SDL Features/Calling a Phone Number/index.md
Fixes #134 
Removed whitespace
> Phone Number

- docs/Displaying a User Interface/Text Images and Buttons/index.md
> Template Titles - Fall 2019 Feature

- docs/Other SDL Features/Retrieving Vehicle Data/index.md
Fixes #157 
This PR adds information about the Generic Network Signal Data proposal.
> Generic Network Signal Data - Fall 2019 Documentation

- docs/Displaying a User Interface/Main Menu/index.md
Fixes #139 #100 
Adding setting a menu layout
> Main Menu Tiles - Fall Documentation 2019

- docs/Getting Started/Adding the Lock Screen/index.md
Fixes #140 #144 #100 
Added new Enum content and dismissible lock screen
> Dismissible Lock Screen / Disable Lock Screen - Fall 2019 Documentation 

- docs/Displaying a User Interface/Popup Menus and Keyboards/index.md
Fixes #137 
This pull request **[updates existing content]**.
Updated content for auto-complete list.
> AutoComplete List - Fall Documentation 2019

- config.json
- docs/Getting Started/Multiple Transports/index.md
Fixes #50 
This pull request **adds**.
Added multiple transport information for iOS
> Multiple Transports

- docs/Displaying a User Interface/Alerts/index.md
- docs/Displaying a User Interface/Popup Menus and Keyboards/index.md
- docs/Displaying a User Interface/Scrollable Message/index.md
- docs/Displaying a User Interface/Slider/index.md
Fixes #100 
Adding cancel interaction documentation
> Cancel interaction documentation - Fall 2019 documentation

- docs/Getting Started/Installation/index.md
This PR updates the installation page to use the latest version of the libraries
> Update the installation page to use the latest version of the libs

- docs/Getting Started/Installation/index.md
Fixes #175 
Update accio installation guide to note 6.4.0
> Update Accio installation

- docs/Getting Started/Adapting to the Head Unit Language/index.md
Redo the android Adapting to the Head Unit Language
> Adapting to the Head Unit Language Android

- docs/Other SDL Features/Using App Services/index.md
Fixes #91
This PR adds content around using the `GetFile` RPC in the context of app service consumers.
> Add GetFile documentation to Using App Services guides

- docs/Getting Started/Installation/index.md
Fixes #176 
Fix broken link in Accio documentation
> Fix Accio Documentation Link

- docs/Displaying a User Interface/Alerts/index.md
- docs/Displaying a User Interface/Main Menu/index.md
Fixes #181 
* Fixed a broken link in **Displaying a User Interface > Main Menu**
* Fixed a broken link in **Displaying a User Interface > Alerts**
> Fixed broken links

- docs/Getting Started/Integration Basics/index.md
Fixes #180 
This pull request **fixes**
Changed header sizes to be correct. Header and SubHeader were the same sizes.
> Fix headers to be different sizes 

- docs/Displaying a User Interface/Alerts/index.md
- docs/Displaying a User Interface/Main Screen Templates/index.md
- docs/Displaying a User Interface/Scrollable Message/index.md
- docs/Displaying a User Interface/Slider/index.md
- docs/Other SDL Features/Calling a Phone Number/index.md
- docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
- docs/Other SDL Features/Retrieving Vehicle Data/index.md
- docs/Other SDL Features/Setting the Navigation Destination/index.md
- docs/Speech and Audio/Getting Microphone Audio/index.md
- docs/Speech and Audio/Playing Spoken Feedback/index.md
- docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
Fixes #168 
This pull request **updates content**.
Changed all cases of checks of resultCode with checking for the success of the response.
> Update documentation to use success value instead of resultCode

- docs/Displaying a User Interface/Popup Menus and Keyboards/index.md
Fixes Issue #191 
This pull request fixes typos in existing content
> Fix Popup Menus and Keyboards Spelling

- docs/Developer Tools/Configuring SDL Logging/index.md
Fixes #197, #200 
This pull request **fixes existing content** and **adds new content**.
* Added information about how file logging works with archive builds.
* Updated instructions on how to get log files from a device.
> Updated the logging to file section

- docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Fixes #198 
Add information about app UI rotation while the app is video streaming.
> Add info about UI rotation while streaming

- docs/Getting Started/Adding the Lock Screen/index.md
Fixes #206 
Added code to show developers how to disable the OEM lockscreen.
> Disable OEM lockscreen logo

- docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Fixes #221 
Added information on how to disable the video background string.
> added info on how to disable video background string

- docs/Getting Started/Installation/index.md
Fixes #150 
Added min versions for each platform.
> Issue 150 bugfix min max os support

- docs/Getting Started/Integration Basics/index.md
Fixes #231 
Adds a note for the developers to avoid starting activities from the background
> Add a note about starting activity from the background

- docs/Other SDL Features/Uploading Files/index.md
Fixes #242 
Under `Other SDL Features/ Uploading Files`
Overwrite property for files documentation already exists for IOS, modifications were made to tags and java code was added
> Added overwrite property to java suite

- docs/Other SDL Features/Encryption/index.md
Fixes #244 
For Encryption, javaSE and javaEE tags were missing.
> Added javeSE and javaEE tags that were missing

- docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
Fixes #234, #209
* Add `isCapabilitySupported` information
* Update with new methods for block and method subscribing
* Clarify a little bit of `supportsSubscriptions` info
> Spring 2020 SCM updates

- docs/Getting Started/Installation/index.md
Fixes #250 
This changes the accio string to a format string so that it doesn't need to be updated every release.
> Change accio string to a format string

- docs/Getting Started/Installation/index.md
Fixes #267 
Updates the iOS installation guide numbering to have consistent indentation
> Update iOS installation guide numbering

- docs/Getting Started/SDK Configuration/index.md
> SDK Configuration Additions for JS

- docs/Getting Started/Checking Supported Features/index.md
> Checking Supported Features Additions for JS

- STYLE_GUIDE.md
Fixes #269 
This pull request **adds new content** (no changes to the actual guides).
Adds a style guide to the project dictating how the guide content should be written.
> Add style guide

- docs/Getting Started/Integration Basics/index.md
> Integration Basics Additions for JS

- docs/Getting Started/Understanding Permissions/index.md
Updates the Understanding Permissions doc to have info for the JS Suite.
> Update Understanding Permissions to have info on the JS Suite

- docs/Getting Started/Adapting to the Head Unit Language/index.md
Update the Head Unit Language docs for the JS Suite.
> Update Head Unit Language for JS Suite

- docs/Getting Started/Installation/index.md
Updates the Installation docs to have info for the JS Suite.
> Add Installation docs for JS Suite

- docs/Getting Started/Example Apps/index.md
> Example Apps Additions for JS

- config.json
- docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
- docs/Customizing Look and Functionality/Customizing the Keyboard/index.md
- docs/Customizing Look and Functionality/Customizing the Template/index.md
Updates the `Customizing Look and Functionality` section for the JavaScript Suite.
> Update Customizing Look and Functionality Section for JS Suite

- config.json
- docs/Other SDL Features/Batch Sending RPCs/index.md
- docs/Other SDL Features/Creating an App Service/index.md
- docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
- docs/Other SDL Features/Encryption - Not Supported/index.md
- docs/Other SDL Features/Encryption/index.md
- docs/Other SDL Features/Getting the Navigation Destination/index.md
- docs/Other SDL Features/Remote Control Vehicle Features/index.md
- docs/Other SDL Features/Retrieving Vehicle Data/index.md
- docs/Other SDL Features/Setting the Navigation Destination/index.md
- docs/Other SDL Features/Uploading Files/index.md
- docs/Other SDL Features/Uploading Images/index.md
- docs/Other SDL Features/Using App Services/index.md
Other SDL Features guide for JS
> Other SDL Features Additions for JS

- docs/Getting Started/Installation/index.md
Fixes #287 
This pull request **fixes existing content** 
Update bintray lines for JavaSE & Android to use 4.11.1
> Update bintray lines to use 4.11.1

- README.md
Fixes #295 
Added information on how to create header links to README.
> updated info for header links

- docs/Displaying a User Interface/Alerts/index.md
- docs/Displaying a User Interface/Scrollable Message/index.md
- docs/Migrating to Newer SDL Versions/Updating to v4.7/index.md
This pull request Update the customButtonName methods in the android/java documentation to use the new customButtonID methods.
> Update docs to reflect customButtonID changes

- docs/Other SDL Features/Remote Control Vehicle Features/index.md
- docs/Other SDL Features/Using App Services/index.md
Partially fixes #306
Updates uses of now deprecated initializers for `SDLButtonPress`.
> Use updated initializer of `SDLButtonPress`

- docs/Getting Started/Integration Basics/index.md
- docs/Getting Started/Understanding Permissions/index.md
Fixes #305 
Updated the code snippets to use the setRpcNotificationListeners method in example apps and in other places where the Java library uses their equivalent method.
> Update JS Suite guides to use new setRpcNotificationListeners method

- docs/Getting Started/Understanding Permissions/index.md
Partially Fixes #306
* Add new methods for iOS 6.7
* Align code
> Update Permissions for iOS 6.7 and Align Code Snippets

- docs/Displaying a User Interface/Template Subscription Buttons/index.md
- docs/Displaying a User Interface/Template Text/index.md
Partially fixes #306
Updated the **Template Subscription Buttons** guide to use the new subscribe button manager APIs.
> Add subscribe button manager API

- docs/Getting Started/Installation/index.md
This pull request **fixes existing content** 
This PR updates gradle compile lines to use 4.12
> Update gradle compile lines to use 4.12

- config.json
- docs/NodeJS Documentation/index.md
Fixes #321 
Adds a mention regarding where to find the NodeJS specific documentation for the JS suite library.
> Add section about seeing NodeJS documentation

- docs/Customizing Look and Functionality/Customizing the Keyboard/index.md
- docs/Customizing Look and Functionality/Customizing the Template/index.md
- docs/Displaying a User Interface/Alerts/index.md
- docs/Displaying a User Interface/Main Screen Templates/index.md
- docs/Displaying a User Interface/Scrollable Message/index.md
- docs/Getting Started/Integration Basics/index.md
- docs/Other SDL Features/Calling a Phone Number/index.md
- docs/Other SDL Features/Creating an App Service/index.md
- docs/Other SDL Features/Encryption/index.md
- docs/Other SDL Features/Remote Control Vehicle Features/index.md
- docs/Other SDL Features/Retrieving Vehicle Data/index.md
- docs/Other SDL Features/Setting the Navigation Destination/index.md
- docs/Other SDL Features/Using App Services/index.md
- docs/Speech and Audio/Getting Microphone Audio/index.md
- docs/Speech and Audio/Playing Audio Indications/index.md
- docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
- docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
Partly Fixes #328
Where applicable Java and Android examples are updated to use chainable setters.
> Make rpc setters chainable

- docs/Other SDL Features/Uploading Files/index.md
Fixes #335
Align java docs with iOS for SdlFile.setOverwrite
> Sdl file overwrite

- docs/Other SDL Features/Retrieving Vehicle Data/index.md
Fixes #348
Added missing documentation for vehicle data
> Added missing documentation for vehicle data

- docs/Getting Started/Adding the Lock Screen/index.md
Fixes #215 
Updates Android Code snippets to include setting lockscreenconfig in the builder
> Update Android Lock Screen docs

- docs/Displaying a User Interface/Main Screen Templates/index.md
- docs/Displaying a User Interface/Popup Keyboards/index.md
- docs/Displaying a User Interface/Popup Menus/index.md
- docs/Displaying a User Interface/Template Subscription Buttons/index.md
- docs/Getting Started/Integration Basics/index.md
Fixes #213 
This PR adds trademarks to HU names
> Add trademarks to head unit names

- docs/Getting Started/Adding the Lock Screen/index.md
Fixes #216 
This PR fixes a grammar issue in the lock screen config page
> Fix grammar in lockscreen page

- docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
- docs/Customizing Look and Functionality/Customizing the Template/index.md
- docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
- docs/Displaying a User Interface/Alerts and Subtle Alerts/index.md
- docs/Displaying a User Interface/Main Menu/index.md
- docs/Displaying a User Interface/Main Screen Templates/index.md
- docs/Displaying a User Interface/Popup Keyboards/index.md
- docs/Displaying a User Interface/Popup Menus/index.md
- docs/Displaying a User Interface/Scrollable Message/index.md
- docs/Displaying a User Interface/Template Custom Buttons/index.md
- docs/Displaying a User Interface/Template Images/index.md
- docs/Migrating to Newer SDL Java Suite Versions/Updating to v5.0/index.md
- docs/Other SDL Features/Creating an App Service/index.md
- docs/Other SDL Features/Encryption/index.md
- docs/Other SDL Features/Remote Control Vehicle Features/index.md
- docs/Other SDL Features/Uploading Files/index.md
- docs/Other SDL Features/Uploading Images/index.md
- docs/Other SDL Features/Using App Services/index.md
- docs/Speech and Audio/Playing Audio Indications/index.md
- docs/Speech and Audio/Setting Up Voice Commands/index.md
- docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
- docs/Video Streaming for Navigation Apps/Introduction/index.md
- docs/Video Streaming for Navigation Apps/Menus/index.md
Fixes #300 
This PR removes the java code placeholders because they don't work in java IDEs as in Xcode
> Remove code placeholders - Java Suite only

- docs/Getting Started/Adding the Lock Screen/index.md
Fixes #345 
Add information about transparent default background.
> Update iOS custom lock screen

- docs/Developer Tools/Configuring SDL Logging/index.md
- docs/Getting Started/Installation/index.md
Fixes #67
This PR adds installation details for swift package manager.
> Add Swift Package Manager installation details

- docs/Getting Started/Integration Basics/index.md
Fixes #110 
This PR adds sample XML code for the router service
> Add SdlRouterService Manifest example

- docs/Getting Started/SDK Configuration/index.md
Fixes #371
With Android 11 we have to add a new permission to our manifest. This PR updates documentation about adding that permission.
> Added info about adding permission for Android R

- docs/Getting Started/Installation/index.md
Fixes #374 
This pull request **[fixes existing content]** 
Update Gradle compile lines for Android and JavaSE
> Update JavaEE and JavaSE gradle compile lines for hotfix 4.12.1

- docs/Getting Started/Installation/index.md
Fixes #375 
This PR updates the gradle compile lines in the guides to use 5.0.0
> Update gradle lines for java suite to 5.0.0

- docs/Getting Started/Installation/index.md
Fixes #377 
This PR updates the min supported SDK for Android to API 16
> Update min supported SDK for Android to API 16

- docs/Customizing Look and Functionality/Customizing the Keyboard/index.md
- docs/Displaying a User Interface/Main Menu/index.md
- docs/Migrating to Newer SDL Versions/Updating to v4.9/index.md
- docs/Video Streaming for Navigation Apps/Introduction/index.md
Fix broken links for popup keyboards and menus
Fixes #368 
Fix broken links for popup keyboards and menus.
> Fix broken links

- docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
Fixes #365
Add iOS tags in haptic touch guides
> Add iOS tags to haptic touch guide

- config.json
- docs/Frequently Asked Questions/React Native/index.md
- docs/Getting Started/Adding the Lock Screen/index.md
- docs/Getting Started/Example Apps/index.md
- docs/Getting Started/Integration Basics - JS/index.md
- docs/Getting Started/Integration Basics - Java/index.md
- docs/Getting Started/Integration Basics - iOS/index.md
- docs/Getting Started/Using AOA Protocol/index.md
- docs/Video Streaming for Navigation Apps/Introduction/index.md
Fixes #61 
This pull request **[fixes existing content]** 
Separate Integration Basics guides to be lib specific
> Separate integration basics guides

- config.json
- docs/Frequently Asked Questions/Kotlin Support/index.md
Fixes #391 
This PR adds a new Kotlin section under FAQs to address common issues.
> Add Kotlin FAQs section

- docs/Developer Tools/Configuring SDL Logging/index.md
- docs/Displaying a User Interface/Slider/index.md
- docs/Getting Started/Adding the Lock Screen/index.md
- docs/Getting Started/Example Apps/index.md
- docs/Getting Started/Installation/index.md
- docs/Getting Started/Integration Basics - JS/index.md
- docs/Migrating to Newer SDL Java Suite Versions/Updating to v4.4/index.md
- docs/Migrating to Newer SDL Java Suite Versions/Updating to v4.5/index.md
- docs/Migrating to Newer SDL Java Suite Versions/Updating to v4.6/index.md
- docs/Migrating to Newer SDL Java Suite Versions/Updating to v4.7/index.md
- docs/Other SDL Features/Using App Services/index.md
- docs/Speech and Audio/Playing Spoken Feedback/index.md
> Cleanup spelling, grammar typos and broken links in guides

- docs/Other SDL Features/Retrieving Vehicle Data/index.md
Fixes #393 
This pull request **adds new conten]**.
This PR updates the vehicle data section include additions for the following proposals:
https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0262-New-vehicle-data-SeatOccupancy.md
https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0269-New-vehicle-data-ClimateData.md
https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0255-Enhance-BodyInformation-vehicle-data.md
> Add new vehicle data

- docs/Other SDL Features/Using App Services/index.md
Fixes #358 
Implement the use of SDLSystemCapabilityManager instead of SDLGetSystemCapabilityResponse to get the capability
> Fixed iOS Using App Services code update

- docs/Displaying a User Interface/Media Clock/index.md
Fixes #410 
Fixes several of the code snippets that either won't do the intended behavior or won't function at all.
> Fix JS code snippet bugs in media clock page

- docs/Getting Started/SDK Configuration/index.md
Removed the old language that stated to add a permission that is now going to be considered sensitive and only given upon receiving Google's approval. Instead, added a section to add the intent queries into the manifest.
> Update Android SDK config with queries

- docs/Video Streaming for Navigation Apps/Video Streaming - Java/index.md
- docs/Video Streaming for Navigation Apps/Video Streaming - iOS/index.md
Fixes #412 
Adds details about how parameters are updated based on capabilities.
Adds details about how to specify a preferredFPS and enable a stable frame rate.
Adds details about how to set Ranges for supported capabilities, how to support all capabilities, and how to disable capabilities of landscape or portrait orientation.
Adds details about how the developer will be notified of view resizes.
> Video streaming updates

- docs/Getting Started/Installation/index.md
Fixes #432 
Updated the installation guides for JavaSuite to reflect change to mavenCentral from jcenter
> Add information for mavenCentral repository

- docs/Getting Started/Integration Basics - JS/index.md
- docs/Getting Started/Integration Basics - Java/index.md
- docs/Getting Started/Integration Basics - iOS/index.md
Fixes #424 
Adds guides for OEM Exclusive Apps support
> Implement SDL-0293 Guides - OEM Exclusive Apps

- docs/Getting Started/Integration Basics - Java/index.md
- docs/Migrating to Newer SDL Java Suite Versions/Updating to v5.1/index.md
Fixes #440
Fix migration guide title and update some tags from note or important to must.
Also add MUST note to migration guide
> Fix migration guide and integration guide

- docs/Getting Started/Installation/index.md
Fixes #433 
This pull request **[fixes existing content]** 
Updated gradle lines
> Change version numbers

- docs/Speech and Audio/Setting Up Voice Commands/index.md
Deleting Voice Commands
Fixes #437 
Section added on how to delete current voice commands in **Speech and Audio > Setting Up Voice Commands**
> Added instructions on how to clear voice commands

- docs/Speech and Audio/Setting Up Voice Commands/index.md
Fixes #438 
A new section added for unsupported voice commands.
> Added information about how empty voice command strings are handled

- docs/Speech and Audio/Setting Up Voice Commands/index.md
Fixes #454 
Updated Setting Up Voice Commands docs to include information about how the library handles duplicate strings that are found in the same voice command array and in different voice commands arrays
> Updated voice commands guide to include more information about duplicate strings

- docs/Getting Started/Example Apps/index.md
Fixes #289 
This PR adds the missing Troubleshooting section to the JavaScript Example Apps page and troubleshooting steps for each transport type.
> Add JavaScript Troubleshooting Section

- docs/Getting Started/Installation/index.md
Fixes #461 
Update Gradle lines for Java Suite 5.2.0 release
> Update gradle lines for Android and javaSE to 5.2.0

- docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
- docs/Customizing Look and Functionality/Customizing the Template/index.md
- docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
- docs/Displaying a User Interface/Alerts and Subtle Alerts/index.md
- docs/Displaying a User Interface/Main Screen Templates/index.md
- docs/Displaying a User Interface/Template Custom Buttons/index.md
- docs/Displaying a User Interface/Template Images/index.md
- docs/Getting Started/Checking Supported Features/index.md
- docs/Other SDL Features/Creating an App Service/index.md
- docs/Other SDL Features/Getting the Navigation Destination/index.md
- docs/Other SDL Features/Remote Control Vehicle Features/index.md
- docs/Other SDL Features/Uploading Files/index.md
- docs/Other SDL Features/Uploading Images/index.md
- docs/Other SDL Features/Using App Services/index.md
- docs/Speech and Audio/Playing Audio Indications/index.md
- docs/Speech and Audio/Setting Up Voice Commands/index.md
Fixes #300 
This PR removes the code placeholder tokens for the JavaScript guides that would only work in Xcode.
> Remove code placeholders for JavaScript

- docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
Fixes #155 
This pull request **[fixes existing content]** [or] **[adds new content]**.
Added documentation on how to post `SDLDidUpdateProjectionView` notification properly
> Added documentation how to post the SDLDidUpdateProjectionView notification properly

- docs/Video Streaming for Navigation Apps/Video Streaming - iOS/index.md
Fixes #478 
Update documentation SDLVideoStreamingRange implementation. **Video Streaming for Navigation Apps -> Video Streaming**
> SDLVideoStreamingRange update

- docs/Displaying a User Interface/Main Menu/index.md
Fixes #473 
Updates the Main Menu page for JavaScript to include details on the MenuManager.
> Update docs for the inclusion of the JavaScript menu manager

- docs/Video Streaming for Navigation Apps/Introduction/index.md
Fixes #481 
This PR adds information about setting up a module for video streaming.
> Add information about Core setup for video stream

- docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
- docs/Displaying a User Interface/Template Custom Buttons/index.md
- docs/Speech and Audio/Playing Spoken Feedback/index.md
Fixes #486 
This pull request fixes existing content
SpeechCapabilities now uses the correct enum value for TEXT. The Template Custom Buttons page fixes one of the JS snippets to not cause a crash in the library anymore.
> Fix incorrect JS snippets

- docs/Getting Started/Integration Basics - Java/index.md
Fixes #483 
Updated minimum supported Android API level to level 16 in [Getting Started - Introduction section](https://github.com/smartdevicelink/sdl_app_library_guides/blob/master/docs/Getting%20Started/Integration%20Basics%20-%20Java/index.md#integration-basics).
> Update min supported Android API to API Level 16

- docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
- docs/Displaying a User Interface/Alerts and Subtle Alerts/index.md
- docs/Displaying a User Interface/Main Menu/index.md
- docs/Displaying a User Interface/Scrollable Message/index.md
- docs/Displaying a User Interface/Template Custom Buttons/index.md
- docs/Getting Started/Adapting to the Head Unit Language/index.md
- docs/Getting Started/Connecting to an Infotainment System/index.md
- docs/Getting Started/Integration Basics - JS/index.md
- docs/Speech and Audio/Playing Spoken Feedback/index.md
- docs/Video Streaming for Navigation Apps/Introduction/index.md
Fixes #490 
This PR includes code updates for using the SdlManagerListener's managerShouldUpdateLifecycleToLanguage method.
> Update JS docs for the inclusion of managerShouldUpdateLifecycleToLanguage

- docs/Migrating to Newer SDL Java Suite Versions/Updating to v4.7/index.md
Fixes #496 
Fix URL and add missing periods to `Lock Screen` section of Android's "Updating to 4.7" Guide.
> Fix Lock Screen Section of Android Updating to 4.7 

- config.json
- docs/Getting Started/Integration Basics - Java/index.md
- docs/Getting Started/SDK Configuration/index.md
- docs/Getting Started/Using AOA Protocol/index.md
- docs/Migrating to Newer SDL Java Suite Versions/Updating to v5.4/index.md
Fixes #494 
This pull request  **adds new content**.
Add a new migration guide section to the documentation
Update AOA guide
Update Integration Basics Guide
Update SDK Configuration Guide
> Initial Android 12 updates

- config.json
- docs/Displaying a User Interface/Main Menu/index.md
- docs/Getting Started/Adapting to the Head Unit Language/index.md
- docs/Getting Started/Installation/index.md
- docs/Getting Started/Integration Basics - JS/index.md
- docs/Getting Started/Integration Basics - Java/index.md
- docs/Getting Started/SDK Configuration/index.md
- docs/Getting Started/Using AOA Protocol/index.md
- docs/Migrating to Newer SDL Java Suite Versions/Updating to v5.4/index.md
- docs/Video Streaming for Navigation Apps/Video Streaming - iOS/index.md
* [Update JavaScript docs for SDL 0289 #490](https://github.com/smartdevicelink/sdl_app_library_guides/issues/490)
* [Add Android 12 Information #494](https://github.com/smartdevicelink/sdl_app_library_guides/issues/494)
* [Fix using deprecated `GetVehicleData` init #466](https://github.com/smartdevicelink/sdl_app_library_guides/issues/466)
* [Update SDLVideoStreamingRange docs #478](https://github.com/smartdevicelink/sdl_app_library_guides/issues/478)
> Spring 2022 Guide Updates

- docs/Displaying a User Interface/Template Subscription Buttons/index.md
Fixes #512
Separate the subscription declarations from the functions to avoid confusion for new users
> Update Subscription Button Code Examples with Clearer Code

- docs/Displaying a User Interface/Template Images/index.md
- docs/Getting Started/Integration Basics - iOS/index.md
Fixes #504
* Added SDLArtwork section
* Adjusted headers to accommodate SDLArtwork section
> Template Images Guide Should Explain Creating an SDLArtwork

- docs/Getting Started/Installation/index.md
Fixes #520 
Update gradle lines for SDL Java Suite 5.5.0
> Update gradle lines for 5.5.0 release for Android and JavaSE

- docs/Displaying a User Interface/Template Custom Buttons/index.md
Fixes #526
This PR replaces two examples using singleton lists in the Java guide, Displaying a User Interface/Template Custom Buttons, with examples using lists
containing multiple items.
> Fix issue #526

- docs/Displaying a User Interface/Main Screen Templates/index.md
Fixes #523 
This pull request **add documentation to explain best way to do screen changes**.
In Main Screen Templates add code to explain how to properly change screens. (iOS only for right now)
> Describe best way to organize screen changes

- docs/Getting Started/Installation/index.md
Fixes #545
This pull request **[fixes existing content]
This PR updates Java Suite guides for SDL 5.6.1 hotfix release.
> Update gradle lines in guides for release

- docs/Getting Started/Installation/index.md
Fixes #551 
Update gradle lines for Java_Suite release 5.7.0
> Update gradle lines for Java_Suite release 5.7.0
